## -*- Mode: CPerl -*-
##
## File: DTA::CAB::Document.pm
## Author: Bryan Jurish <moocow@ling.uni-potsdam.de>
## Description: generic API for whole documents passed to/from DTA::CAB::Analyzer

package DTA::CAB::Document;
use DTA::CAB::Datum;
use Carp;
use strict;

##==============================================================================
## Globals
##==============================================================================

our @ISA = qw(DTA::CAB::Datum);

##==============================================================================
## Constructors etc.
##==============================================================================

## $doc = CLASS_OR_OBJ->new(\@sentences,%args)
##  + object structure: HASH
##    {
##     body => \@sentences,  ##-- DTA::CAB::Sentence objects
##     ##
##     ##-- dta-tokwrap attributes
##     xmlbase => $base,
##    }
sub new {
  return bless({
		body => ($#_>=1 ? $_[1] : []),
		@_[2..$#_],
	       }, ref($_[0])||$_[0]);
}

##==============================================================================
## Methods: ???
##==============================================================================

## $n = $doc->nTokens()
sub nTokens {
  my $ntoks = 0;
  $ntoks += scalar(@{$_->{tokens}}) foreach (@{$_[0]->{body}});
  return $ntoks;
}

1; ##-- be happy

__END__

##========================================================================
## POD DOCUMENTATION, auto-generated by podextract.perl & edited

##========================================================================
## NAME
=pod

=head1 NAME

DTA::CAB::Document - generic API for whole documents passed to/from DTA::CAB::Analyzer

=cut

##========================================================================
## SYNOPSIS
=pod

=head1 SYNOPSIS

 use DTA::CAB::Document;
 
 $doc = CLASS_OR_OBJ->new(\@sentences,%args);
 $n = $doc->nTokens();

=cut

##========================================================================
## DESCRIPTION
=pod

=head1 DESCRIPTION

=cut

##----------------------------------------------------------------
## DESCRIPTION: DTA::CAB::Document: Globals
=pod

=head2 Globals

=over 4

=item Variable: @ISA

DTA::CAB::Document inherits from
L<DTA::CAB::Datum|DTA::CAB::Datum>.

=back

=cut

##----------------------------------------------------------------
## DESCRIPTION: DTA::CAB::Document: Constructors etc.
=pod

=head2 Constructors etc.

=over 4

=item new

 $doc = CLASS_OR_OBJ->new(\@sentences,%args);

%args, %$doc:

 body => \@sentences,  ##-- DTA::CAB::Sentence objects

=back

=cut

##----------------------------------------------------------------
## DESCRIPTION: DTA::CAB::Document: Methods: ???
=pod

=head2 Methods

=over 4

=item nTokens

 $n = $doc->nTokens();

Returns number of tokens in the document.

=back

=cut

##========================================================================
## END POD DOCUMENTATION, auto-generated by podextract.perl

##======================================================================
## Footer
##======================================================================

=pod

=head1 AUTHOR

Bryan Jurish E<lt>jurish@bbaw.deE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2009 by Bryan Jurish

This package is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.4 or,
at your option, any later version of Perl 5 you may have available.

=cut


=cut
