## -*- Mode: CPerl -*-
##
## File: DTA::CAB::Analyzer::Eqlemma
## Author: Bryan Jurish <jurish@uni-potsdam.de>
## Description: lemma-equivalence class expansion: default

##==============================================================================
## Package: Analyzer::Morph
##==============================================================================
package DTA::CAB::Analyzer::EqLemma;
use strict;

use DTA::CAB::Analyzer::EqLemma::BDB;
our @ISA = qw(DTA::CAB::Analyzer::EqLemma::BDB);

1; ##-- be happy

__END__

##========================================================================
## POD DOCUMENTATION, auto-generated by podextract.perl, edited

##========================================================================
## NAME
=pod

=head1 NAME

DTA::CAB::Analyzer::EqLemma - lemma-equivalence class expander: default

=cut

##========================================================================
## SYNOPSIS
=pod

=head1 SYNOPSIS

 ##========================================================================
 ## PRELIMINARIES
 
 use DTA::CAB::Analyzer::EqLemma;
 

=cut

##========================================================================
## DESCRIPTION
=pod

=head1 DESCRIPTION

This class is just a convenience wrapper for
L<DTA::CAB::Analyzer::EqLemma::BDB|DTA::CAB::Analyzer::EqLemma::BDB>.

=cut

##========================================================================
## END POD DOCUMENTATION, auto-generated by podextract.perl
=pod



=cut

##======================================================================
## Footer
##======================================================================
=pod

=head1 AUTHOR

Bryan Jurish E<lt>jurish@bbaw.deE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2011 by Bryan Jurish

This package is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.10.0 or,
at your option, any later version of Perl 5 you may have available.

=head1 SEE ALSO

L<dta-cab-analyze.perl(1)|dta-cab-analyze.perl>,
L<DTA::CAB::Analyzer::EqLemma::BDB(3pm)|DTA::CAB::Analyzer::EqLemma::BDB>,
L<DTA::CAB::Analyzer(3pm)|DTA::CAB::Analyzer>,
L<DTA::CAB::Chain(3pm)|DTA::CAB::Chain>,
L<DTA::CAB(3pm)|DTA::CAB>,
L<perl(1)|perl>,
...



=cut
