## -*- Mode: CPerl -*-
##
## File: DTA::CAB::Analyzer::EqPho
## Author: Bryan Jurish <jurish@uni-potsdam.de>
## Description: phonetic equivalence class expansion: default

##==============================================================================
## Package: Analyzer::Morph
##==============================================================================
package DTA::CAB::Analyzer::EqPho;
use strict;
#use DTA::CAB::Analyzer::EqPho::FST;
#our @ISA = qw(DTA::CAB::Analyzer::EqPho::FST);
##
use DTA::CAB::Analyzer::EqPho::DB;
our @ISA = qw(DTA::CAB::Analyzer::EqPho::DB);


1; ##-- be happy

__END__

##========================================================================
## POD DOCUMENTATION, auto-generated by podextract.perl, edited
=pod

=cut

##========================================================================
## NAME
=pod

=head1 NAME

DTA::CAB::Analyzer::EqPho - phonetic equivalence class expander

=cut

##========================================================================
## SYNOPSIS
=pod

=head1 SYNOPSIS

 use DTA::CAB::Analyzer::EqPho;
 
 $eqp = DTA::CAB::Analyzer::EqPho->new(%args);
 $eqp->analyze($tok);

=cut

##========================================================================
## DESCRIPTION
=pod

=head1 DESCRIPTION

Default phonetic equivalence class expander.
Just a wrapper for L<DTA::CAB::Analyzer::EqPho::DB|DTA::CAB::Analyzer::EqPho::DB>.

=cut

##========================================================================
## END POD DOCUMENTATION, auto-generated by podextract.perl

##======================================================================
## Footer
##======================================================================

=pod

=head1 AUTHOR

Bryan Jurish E<lt>jurish@bbaw.deE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2009-2010 by Bryan Jurish

This package is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.4 or,
at your option, any later version of Perl 5 you may have available.

=cut

