## -*- Mode: CPerl -*-
##
## File: DTA::CAB::Analyzer::EqPhoX
## Author: Bryan Jurish <moocow@ling.uni-potsdam.de>
## Description: phonetic equivalence class expansion: restricted to extant target language

##==============================================================================
## Package: Analyzer::Morph
##==============================================================================
package DTA::CAB::Analyzer::EqPhoX;
use DTA::CAB::Analyzer::EqPho::Cascade;
use strict;
our @ISA = qw(DTA::CAB::Analyzer::EqPho::Cascade);

## $obj = CLASS_OR_OBJ->new(%args)
##  + object structure: see DTA::CAB::Analyzer::Automaton::Gfsm::XL
sub new {
  my $that = shift;
  my $aut = $that->SUPER::new(
			      ##-- defaults

			      ##-- analysis selection
			      label => 'eqphox',
			      analyzeGet => '$_[0]{lts} ? (map {$_->{hi}} @{$_[0]{lts}}) : qw()',
			      attInput   => 1,
			      allowTextRegex => '(?:^[[:alpha:]\-]*[[:alpha:]]+$)|(?:^[[:alpha:]]+[[:alpha:]\-]+$)',
			      tolower=>0,
			      tolowerNI=>0,
			      toupperI=>0,

			      ##-- analysis parameters
			      max_weight => [1.2,10],
			      max_paths  => 8,
			      max_ops    => -1,

			      ##-- user args
			      @_
			     );
  return $aut;
}

1; ##-- be happy

__END__

##========================================================================
## POD DOCUMENTATION, auto-generated by podextract.perl, edited
=pod

=cut

##========================================================================
## NAME
=pod

=head1 NAME

DTA::CAB::Analyzer::EqPho - phonetic equivalence class expander

=cut

##========================================================================
## SYNOPSIS
=pod

=head1 SYNOPSIS

 use DTA::CAB::Analyzer::EqPhoX;
 
 $eqp = DTA::CAB::Analyzer::EqPhoX->new(%args);
 $eqp->analyze($tok);

=cut

##========================================================================
## DESCRIPTION
=pod

=head1 DESCRIPTION

Default phonetic equivalence class expander using an extant target language.
Just a wrapper for L<DTA::CAB::Analyzer::EqPho::FST|DTA::CAB::Analyzer::EqPho::Cascade>.

=cut

##========================================================================
## END POD DOCUMENTATION, auto-generated by podextract.perl

##======================================================================
## Footer
##======================================================================

=pod

=head1 AUTHOR

Bryan Jurish E<lt>jurish@bbaw.deE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2010 by Bryan Jurish

This package is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.4 or,
at your option, any later version of Perl 5 you may have available.

=cut

