## -*- Mode: CPerl -*-
##
## File: DTA::CAB::Analyzer::EqRW
## Author: Bryan Jurish <jurish@uni-potsdam.de>
## Description: phonetic equivalence class expansion: default

##==============================================================================
## Package: Analyzer::Morph
##==============================================================================
package DTA::CAB::Analyzer::EqRW;
use strict;

#use DTA::CAB::Analyzer::EqRW::FST;
#our @ISA = qw(DTA::CAB::Analyzer::EqRW::FST);
##--
use DTA::CAB::Analyzer::EqRW::DB;
our @ISA = qw(DTA::CAB::Analyzer::EqRW::DB);

1; ##-- be happy

__END__

##========================================================================
## POD DOCUMENTATION, auto-generated by podextract.perl, edited
=pod

=cut

##========================================================================
## NAME
=pod

=head1 NAME

DTA::CAB::Analyzer::EqRW - default rewrite equivalence class expander

=cut

##========================================================================
## SYNOPSIS
=pod

=head1 SYNOPSIS

 use DTA::CAB::Analyzer::EqRW;
 
 $eqp = DTA::CAB::Analyzer::EqRW->new(%args);

=cut

##========================================================================
## DESCRIPTION
=pod

=head1 DESCRIPTION

Default rewrite equivalence class expander.
Just a wrapper for L<DTA::CAB::Analyzer::EqRW::DB|DTA::CAB::Analyzer::EqRW::DB>.

=cut

##========================================================================
## END POD DOCUMENTATION, auto-generated by podextract.perl

##======================================================================
## Footer
##======================================================================

=pod

=head1 AUTHOR

Bryan Jurish E<lt>jurish@bbaw.deE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2009-2010 by Bryan Jurish

This package is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.4 or,
at your option, any later version of Perl 5 you may have available.

=cut

