## -*- Mode: CPerl -*-
##
## File: DTA::CAB::Analyzer::Latin.pm
## Author: Bryan Jurish <moocow@ling.uni-potsdam.de>
## Description: auxiliary latin-language analysis via Gfsm automata

##==============================================================================
## Package: Analyzer::Latin
##==============================================================================
package DTA::CAB::Analyzer::Latin;
use DTA::CAB::Analyzer::Dict;
use Carp;
use strict;
our @ISA = qw(DTA::CAB::Analyzer::Dict);

## $obj = CLASS_OR_OBJ->new(%args)
##  + object structure: see DTA::CAB::Analyzer::Automaton::Gfsm
sub new {
  my $that = shift;
  my $aut = $that->SUPER::new(
			      ##-- analysis selection
			      analyzeDst => 'latin',
			      tolower => 1,

			      ##-- user args
			      @_
			     );
  return $aut;
}

##==============================================================================
## Analysis Formatting
##==============================================================================


1; ##-- be happy

__END__
##========================================================================
## POD DOCUMENTATION, auto-generated by podextract.perl
=pod

=cut

##========================================================================
## NAME
=pod

=head1 NAME

DTA::CAB::Analyzer::Latin - auxilliary latin word recognizer via external dictionary

=cut

##========================================================================
## SYNOPSIS
=pod

=head1 SYNOPSIS

 use DTA::CAB::Analyzer::Latin;
 
 $latin = DTA::CAB::Analyzer::Latin->new(%args);
 $latin->analyze($tok);

=cut

##========================================================================
## DESCRIPTION
=pod

=head1 DESCRIPTION

DTA::CAB::Analyzer::Latin
is a just a simplified wrapper for
L<DTA::CAB::Analyzer::Dict|DTA::CAB::Analyzer::Dict>
which sets the following default options:

 ##-- analysis selection
 analyzeDst => 'latin',   ##-- analysis output property

=cut

##========================================================================
## END POD DOCUMENTATION, auto-generated by podextract.perl

##======================================================================
## Footer
##======================================================================

=pod

=head1 AUTHOR

Bryan Jurish E<lt>jurish@bbaw.deE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2009 by Bryan Jurish

This package is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.4 or,
at your option, any later version of Perl 5 you may have available.

=cut
