## -*- Mode: CPerl -*-
##
## File: DTA::CAB::Analyzer::EqRW::FST.pm
## Author: Bryan Jurish <moocow@ling.uni-potsdam.de>
## Description: phonetic equivalence class expansion via Gfsm::Automaton

##==============================================================================
## Package: Analyzer::Morph
##==============================================================================
package DTA::CAB::Analyzer::EqRW::FST;
use DTA::CAB::Analyzer::Automaton::Gfsm;
use Carp;
use strict;
our @ISA = qw(DTA::CAB::Analyzer::Automaton::Gfsm);

## $obj = CLASS_OR_OBJ->new(%args)
##  + object structure: see DTA::CAB::Analyzer::Automaton::Gfsm, DTA::CAB::Analyzer::Automaton
sub new {
  my $that = shift;
  my $aut = $that->SUPER::new(
			      ##-- overrides
			      #tolower => 0,
			      #check_symbols => 0,

			      ##-- analysis selection
			      #analysisClass => 'DTA::CAB::Analyzer::EqRW::FST::Analysis',
			      label => 'eqrw',
			      analyzeGet     => ('($_[0]{rw} && @{$_[0]{rw}} ? (map {$_->{hi}} @{$_[0]{rw}})'
						 .': ($_[0]{xlit} ? $_[0]{xlit}{latin1Text} : $_[0]{text}))'),
			      attInput       => 1,
			      wantAnalysisLo => 1,
			      allowTextRegex => '(?:^[[:alpha:]\-]*[[:alpha:]]+$)|(?:^[[:alpha:]]+[[:alpha:]\-]+$)',
			      #allowWordRegex => '.',

			      ##-- user args
			      @_
			     );
  return $aut;
}

## $doc = $anl->analyzeTypes($doc,\%types,\%opts)
##  + perform type-wise analysis of all (text) types in %types (= %{$doc->{types}})
##  + extracts rewrite targets, builds pseudo-type hash, calls sub-chain analyzeTypes(), & expands
sub analyzeTypesNope {
  my ($anl,$doc,$types,$opts) = @_;

  ##-- load
  $anl->ensureLoaded();
  $types = $doc->types if (!$types);

  ##-- analyze all
  my $aword    = $anl->getAnalyzeWordClosure();
  my $aget_txt = $anl->accessClosure($anl->{analyzeGet}   || '$_[0]{text}');
  my $aget_rw  = $anl->accessClosure($anl->{analyzeGetRw} || 'qw()');
  my $aset     = $anl->accessClosure($anl->{analyzeSet}   || '$_[0]{$anl->{label}}=$_[1]');

  ##-- ye olde loope
  my ($tok,$w,$a_w, @rw,$rw,$a_rw);
  foreach $tok (values %$types) {
    $w  = $aget_txt->($tok);
    @rw = $aget_rw->($tok);
    $a_w =  $aword->($w,$opts);
    $a   = 0; ##-- CONTINUE HERE
    foreach $rw (@rw) {
      $a_rw =  0; ##-- CONTINUE HERE
    }
    $aset->($tok,$a);
  }

  ##-- return
  return $doc;
}

1; ##-- be happy

__END__

##========================================================================
## POD DOCUMENTATION, auto-generated by podextract.perl, edited
=pod

=cut

##========================================================================
## NAME
=pod

=head1 NAME

DTA::CAB::Analyzer::EqRW::FST - FST-based rewrite-equivalence expander

=cut

##========================================================================
## SYNOPSIS
=pod

=head1 SYNOPSIS

 use DTA::CAB::Analyzer::EqRW::FST;
 
 $eqp = DTA::CAB::Analyzer::EqRW::FST->new(%args);
 $eqp->analyze($tok);

=cut

##========================================================================
## DESCRIPTION
=pod

=head1 DESCRIPTION

B<WORK IN PROGRESS>

L<Gfsm::Automaton|Gfsm::Automaton>-based rewrite-equivalence-class expander.
Composite analyzers should also include a 'rw' rewrite analyzer.

DTA::CAB::Analyzer::EqRW::FST
is a just a simplified wrapper for
L<DTA::CAB::Analyzer::Automaton::Gfsm|DTA::CAB::Analyzer::Automaton::Gfsm>
which sets the following default options:

 analyzeSrc     => 'rw',     ##-- analysis input property
 analyzeDst     => 'eqrw',   ##-- analysis output property
 attInput       => 1,        ##-- respect AT&T-lextools escapes in input strings
 wantAnalysisLo => 1,        ##-- include lower label paths in output
 allowTextRegex => '(?:^[[:alpha:]\-]*[[:alpha:]]+$)|(?:^[[:alpha:]]+[[:alpha:]\-]+$)',
                             ##-- analyze only "alphabetic" tokens

=cut

##========================================================================
## END POD DOCUMENTATION, auto-generated by podextract.perl

##======================================================================
## Footer
##======================================================================

=pod

=head1 AUTHOR

Bryan Jurish E<lt>jurish@bbaw.deE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2009 by Bryan Jurish

This package is free software; you can redistribute it and/or modify
it under the same terms as Perl itself, either Perl version 5.8.4 or,
at your option, any later version of Perl 5 you may have available.

=cut


=cut
